now generates player data per realm, guild data uses this data
thekroko/uthgard-herald pull request #21
Opened 2017-01-24 22:41 UTC by Donutttt

Should pave the way for guild pages being able to list player data.

2017-01-25 02:46 UTC, burfo requested changes
I'm fine with merging this, but there's actually 1 error that you probably should fix.   :)

2017-01-25 02:46 UTC, burfo commented on herald/generate-player-data.js
> +let playerNames.push('Testplayer');
This is actually an error.  You can't redeclare `playerNames`, it's already declared on line 144.

2017-01-25 09:15 UTC, Donutttt commented on herald/generate-player-data.js
> +let playerNames.push('Testplayer');
I'm suprised that worked at all, it's just a typo really, there's no need for `let` there at all. It's not actually redeclaring playerNames I don't think, but presumably declaring whatever `playerNames.push` evaluates to.

In any case I can fix this later on today.

2017-01-26 01:37 UTC, burfo commented on herald/generate-player-data.js
> +let playerNames.push('Testplayer');
Well that's the thing, it didn't work for me.  It errored with a SyntaxError at runtime.
```
\herald\generate-player-data.js:163
let playerNames.push('Testplayer');
    ^^^^^^^^^^^
SyntaxError: Identifier 'playerNames' has already been declared
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```
Thanks for fixing it!

2017-01-26 01:38 UTC, merged

2017-01-26 12:44 UTC, Donutttt commented on herald/generate-player-data.js
> +let playerNames.push('Testplayer');
Ah interesting, perhaps I may have edited it by mistake after commiting, hopefully that'll be ifne now