Home page search improvements
thekroko/uthgard-herald pull request #49
Opened 2017-02-21 23:20 UTC by Donutttt

still not really styled, but you can now press enter to search, and you can now click a player's name to visit their profile

2017-02-21 23:22 UTC, andir commented
LGTM 👍

2017-02-22 03:51 UTC, burfo requested changes
Nice work!  Please fix the lint errors.

P.S. you can run the lint `npm run lint` and the tests `npm run test` beforehand to see these errors.

2017-02-22 15:10 UTC, andir commented on herald/src/app/shared/data-table/data-table.component.ts
> +        console.dir(foundWord);
how are we gonna deal with those debug statements in the future? Just carry them along? Is there some kind of angular debugging that only works once enabled/in dev mode?

2017-02-22 16:54 UTC, Donutttt commented on herald/src/app/shared/data-table/data-table.component.ts
> +        console.dir(foundWord);
Would be good, at the moment I'm just logging stuff but it'll need to be changed at some point

2017-02-22 23:53 UTC, merged